# Generated by Django 4.1.4 on 2022-12-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_thumbnails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
    ]
